version: '3'

services:
  # React App
  todo-client:
    restart: always
    build:
      dockerfile: ./apps/todo-client/Dockerfile
      target: develop
    command: npm run todo-client:dev:docker
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
    ports:
      - 4200:4200

  # Nest Api
  todo-api:
    restart: always
    build:
      dockerfile: ./apps/todo-api/Dockerfile
      target: develop
    command: npm run todo-api:dev:docker
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  mono-node-modules: null
