version: '3'

services:
  # React App
  todo-client:
    restart: always
    build:
      dockerfile: ./apps/todo-client/Dockerfile
      target: develop
    command: npm run todo-client:dev:docker
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
    ports:
      - 4200:4200

  # Nest Api
  todo-api:
    restart: always
    build:
      dockerfile: ./apps/todo-api/Dockerfile
      target: develop
    command: npm run todo-api:dev:docker
    depends_on:
      - mongo
    environment:
      - DEV_PLATFORM=DOCKER
      - MONGODB_URL=mongodb://user:password@mongo:27017/
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
    ports:
      - 3000:3000
    networks:
      - node-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    networks:
      - node-network

volumes:
  mono-node-modules: null

networks:
  node-network:
    driver: bridge
